# Generated by Django 3.2 on 2021-04-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_booking_model_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='end_time',
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
