# Generated by Django 3.2 on 2021-04-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20210429_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
