# Generated by Django 3.2 on 2021-04-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_booking_model_booked_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_model',
            old_name='booked_id',
            new_name='booking_id',
        ),
    ]
