# Generated by Django 3.2 on 2021-04-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_rename_booked_id_booking_model_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='booking_model',
            name='expired',
        ),
    ]
