# Generated by Django 3.2 on 2021-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20210430_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='booking_id',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='booking_model',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
