# Generated by Django 3.2 on 2021-05-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20210430_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='booked_time',
            field=models.TimeField(null=True),
        ),
    ]
