# Generated by Django 3.2 on 2021-05-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_booking_model_booked_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='booked_time',
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='booked_time',
            field=models.TimeField(null=True),
        ),
    ]
