# Generated by Django 3.2 on 2021-05-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20210501_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_model',
            name='models',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
