# Generated by Django 3.2 on 2021-05-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_booking_model_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_model',
            name='models',
        ),
        migrations.AddField(
            model_name='parking_slot',
            name='available_increment',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
